/*
DO NOT ENTER QUESTIONS DIRECTLY HERE. ENTER THEM IN THE ALT GOOGLE DRIVE, THEN COPY THE CODE FROM THAT SHEET:
https://docs.google.com/spreadsheets/d/19khT-ikYMGm2o9fahbKq1aHtGj-_kiY8CQ4I0LLgqUM/edit?gid=0#gid=0
*/

const faqs = [

{id:1, q:"How do I view/update my Profile?", a:"In the top nav click 'My Profile'.", tags:"General,Standard User"}
, {id:2, q:"On the Member Management page, what do all the boxes mean?", a:"https://scribehow.com/page/Glossary_and_Setup_Screen__vcmqgTN1QwacaXj7e6PsXA?referrer=documents", tags:"General,Admin"}
, {id:3, q:"How do I create an event in the calendar?", a:"In the top nav click 'Calendar', then click the calendar you want.\nClick the grey button 'Manage', then click 'Add Event'.", tags:"Calendar,Admin"}
, {id:4, q:"How do I edit/manage/update an event?", a:"In the top nav click 'Calendar', then click the calendar you want.\nClick the grey button 'Manage', then click 'Calendar'. (NOTE: This webpage will look exactly like the same calendar but now when you click on an event, you can edit it). Alternatively, you can click 'Manage' > 'List' to see the calendar as a list.\nFind your event and click it.", tags:"Calendar,Admin"}
, {id:5, q:"How do I remove/delete an event?", a:"In the top nav click 'Calendar', then click the calendar you want.\nClick the grey button 'Manage', then click 'List'.\nFind your event and click the 'Delete' icon.", tags:"Calendar,Admin"}
, {id:6, q:"How do I create shifts for an event?", a:"https://scribehow.com/viewer/How_to_create_sub-registrations_in_an_event__P0MMDw5LQR-aAyXZIMzWZg", tags:"Calendar,Admin"}
, {id:7, q:"How do I sign up for an event?", a:"In the top nav click 'Calendar', then click the calendar you want.\nFind the event you want and click it.\nAdd any comments in the 'Comments' box. Then click 'Register'.", tags:"Calendar,Standard User"}
, {id:8, q:"How do I set up email reminders for events?", a:"(This is a calendar feature and cannot be set per event)\nIn the top nav click 'Calendar', then click the calendar you want.\nClick the grey button 'Setup'.\nScroll down and click on 'Reminder Emails'.", tags:"Calendar,Admin"}
, {id:9, q:"How do I send a message to participants who are registered for an event?", a:"See the how-to for 'Manage an Event'.", tags:"Calendar,Admin"}
, {id:10, q:"How do I set up membership dues?", a:"https://scribehow.com/viewer/Set_Dues_Definitions__ksYc9xazR9qN-0Sy2DEO8g?referrer=knowledge-page", tags:"Membership"}
, {id:11, q:"How do I set up the onboarding process for new members?", a:"https://scribehow.com/page/Checklists_for_Onboarding_and_Renewal__tzs4Kgn7SHWO5yifG_5qeg?referrer=page&slug=/page/Member_and_Dues_Management__41AlR8ruRz64zD9x28H0Xg?referrer=documents", tags:"Membership"}
, {id:12, q:"I'd like to onboard a new member for them by entering their info. How do i do that?", a:"https://scribehow.com/viewer/Create_a_New_Member_in_League_Link__OqeTSgSWSOSb3uuzbwxICw?referrer=knowledge-page", tags:"Membership,Admin"}
, {id:13, q:"How do I renew my membership?", a:"An admin will assign your renewal. Once that happens, you'll see the checklist on your homepage in the box 'My Checklists'.", tags:"Membership,Standard User"}
, {id:14, q:"How do I set multiple members to \"Inactive\"?", a:"In the top nav click 'Administration' then 'Member Management'.\nScroll down and click 'Status Mass Assign\nFind the accounts you want to assign and fill out the rest of the form.", tags:"Membership,Admin"}
, {id:15, q:"How do I set up leadership positions?", a:"In the top nav click 'Administration' then 'Member Management'.\nScroll down and click 'Position Manager'.", tags:"Membership"}
, {id:16, q:"How do I create a group?", a:"https://scribehow.com/page/Permissions_and_Access_GroupsGroupShare___qMB-xffSJiBEB5wGyLNaQ#heading-2", tags:"Membership,Admin"}
, {id:17, q:"How do I assign the renewal process to a member?", a:"\"In the top nav click 'Administration' then 'Member Management'.\nClick 'Checklist Queue'.\nClick the '+' sign.\nUnder 'Checklist' select 'Adult Membership Renewal'.\nUnder 'Account' search for the member name.", tags:"Membership,Admin"}
, {id:18, q:"How do I log hours for an event that I volunteered for?", a:"On your homepage, look for the box title 'Enter Hours'.\nClick the button 'Add Hours'.\nComplete the form. If you don't see your event, let your event coordinator know to add the event in the calendar.", tags:"Hours,Standard User"}
, {id:19, q:"How do I log hours for someone else?", a:"In the top nav click 'Administration' then 'Member Management'.\nClick 'Hours Manager'.\nClick the blue button 'Add'.", tags:"Hours,Admin"}
, {id:20, q:"How do I add categories/activites for hours?", a:"https://scribehow.com/viewer/How_To_Add_Hours_Categories_and_Activities_In_LeagueLink__TdTOdOl6RhijEfCXlLFEKg", tags:"Hours,Admin"}
, {id:21, q:"How do I edit the status and/or status date of a member?", a:"Click 'Administration', then 'Member Search'.\nFind the member.\nScroll down about 1 page to 'Volunteer/Employee Status'.\nClick the Edit icon on the status you want to edit.", tags:"Membership,Admin"}
, {id:22, q:"When editing a step in a checklist, what does \"Step Type\" mean?", a:"https://scribehow.com/page/Checklists_for_Onboarding_and_Renewal__tzs4Kgn7SHWO5yifG_5qeg?referrer=page&slug=/page/Member_and_Dues_Management__41AlR8ruRz64zD9x28H0Xg#heading-5", tags:"Checklists,Admin"}
, {id:23, q:"When editing a step in a checklist, what do all the options mean?", a:"https://scribehow.com/page/Checklists_for_Onboarding_and_Renewal__tzs4Kgn7SHWO5yifG_5qeg?referrer=page&slug=/page/Member_and_Dues_Management__41AlR8ruRz64zD9x28H0Xg#heading-5", tags:"Checklists,Admin"}
, {id:24, q:"I tried including the step \"Parent/Guardian Consent Request\" in my Assisteens Intake checklist but it doesn't do anything. What am I doing wrong?", a:"In the step set up, ensure that the field \"End User Link\" is populate with the following value: /?nd=vms_minor_consent", tags:"Membership,Checklists,Assisteens,Admin"}
, {id:25, q:"I tried deleting a status and it won't work. What's going on?", a:"Statuses can only be deleted if they aren't assigned to anyone, which includes both past and present statuses. You'll have to use the Query Tool to find everyone that is assigned a specific status.", tags:"General,Admin"}
, {id:26, q:"In Access Manager, when assigning someone access, the dropdown box \"Access Levels\" has so many options. What do they mean?", a:"(need to upload image from digital cheetah)", tags:"General,Admin"}
, {id:27, q:"How do I create a group, aka GroupShare, to collaborate with certain people?", a:"https://scribehow.com/viewer/How_to_Create_an_Access_Group_and_add_Members_for_a_Committee_or_other_Group__2up5yxzKTCyRUFkwC6bKlA?referrer=knowledge-page", tags:"Groups,Admin"}
, {id:28, q:"How do I delete a group, aka GroupShare?", a:"Deleting an Access Group will also delete its GroupShare. Wait overnight to take effect or click \"Refresh GroupShare\" on the bottom of the Access Group Manager page.", tags:"Groups,Admin"}
, {id:29, q:"What do prospective Assisteens see when they get to the Parent/Guardian Consent Step?", a:"https://scribehow.com/viewer/Assisteen_Guardian_Consent_Process__3eF6euorRbqp7Xy0CcYIcQ", tags:"Membership,Checklists,Assisteens,Admin"}
, {id:30, q:"How do I delete/remove a member?", a:"Note: You need the Member Administrator administrative access level.\nClick 'Administration', then 'Member Search', then find and click on the member.\nScroll down about one page to 'Volunteer/Member Status'. Then click 'Inactivate Member'.\nUnder 'Status Name', select 'Delete'. Fill out the other fields as needed.\nClick 'Submit'.", tags:"Accounts,Admin"}
, {id:31, q:"How do I use the Parent/Guardian Consent Step for the Assisteen Intake Checklist?", a:"Ensure you add two steps in your Assisteen Intake checklist:\n1. Parent/Guardian Consent Request - This step prompts the Assisteen to enter their parent/guardian information.\n2. Parent/Guardian Consent Completed - This step sends an email to the parent/guardian. Once the parent/guardian responds, the step will be completed.", tags:"Membership,Checklists,Assisteens,Admin"}
, {id:32, q:"If a member joins late in the membership year and we let them know that their dues will apply to the following year as well, how do we record this?", a:"Navigate to their profile. Click Administration > Member Search > find their name and click on it.\nScroll about a page down to 'Volunteer/Employee Status'.\nClick 'Add New Status'.\nSet 'Status Name' to Active Member and 'Effective Date' to June 1 of the next membership year.", tags:"Membership,Admin"}
, {id:33, q:"After creating the new member checklist/process, how do I test it? ", a:"https://scribehow.com/viewer/How_to_Create_a_Test_User__Go1fvS3WTD6NhFNmzDm_cA", tags:"Membership,Checklists,Admin"}
, {id:34, q:"After creating the membership renewal checklist/process, how do I test it? ", a:"(Optional) Create a test member (see FAQ for creating a test member).\nIn the top nav click 'Administration' then 'Member Management'.\nClick 'Checklist Queue'.\nClick the '+' sign.\nUnder 'Checklist' select 'Adult Membership - Renewal'.\nUnder 'Account' search for the member name.", tags:"Membership,Checklists,Admin"}
, {id:35, q:"How do I create a test member?", a:"https://scribehow.com/viewer/How_to_Create_a_Test_User__Go1fvS3WTD6NhFNmzDm_cA", tags:"Accounts,Admin"}
, {id:36, q:"How can I set voting/non-voting status for members?", a:"https://scribehow.com/viewer/Set_and_Manage_Member_StatusesClassifications__aftgUoT_RAGZGNVejX_z5g?referrer=knowledge-page", tags:"General,Admin"}
, {id:37, q:"What does \"Member Status\" mean and how do I create/manage them?", a:"https://scribehow.com/viewer/Set_and_Manage_Member_StatusesClassifications__aftgUoT_RAGZGNVejX_z5g?referrer=knowledge-page", tags:"General,Admin"}
, {id:38, q:"On top of member dues, I want to charge add-on/additional fees associated with membership. How do I do that?", a:"https://scribehow.com/viewer/Add_Dues_Add-Ons_to_Dues__yhSXycPwQauuMbpot-3K2w?referrer=knowledge-page", tags:"Dues,Admin"}
, {id:39, q:"How do I bulk assign a Member Status to multiple members?", a:"https://scribehow.com/viewer/Bulk_AssignMass_Assign_Member_Status_for_Multiple_Members__0Cy6iebwRzKVbXju6J8Nkg?referrer=knowledge-page", tags:"General,Admin"}
, {id:40, q:"I've set up my Dues and assigned them to a checklist, but when I test it the member's status doesn't change. What am I missing?", a:"https://scribehow.com/viewer/Assign_Member_Statuses_to_Dues_Definitions_with_Dues_Status_Listing__-Cbs97UzS5S-6CI5cDopiw?referrer=knowledge-page", tags:"Dues,Admin"}
, {id:41, q:"How do I add steps to a checklist?", a:"Click 'Administration', then 'Member Management', then \"Checklist Configuration Local\".\nClick the \"Cog\" icon next to the checklist you want to edit.\nClick the \"+\" sign to add a step. Once you've finished setting up the step, you can rearrange the order on this screen.", tags:"Checklists,Admin"}
, {id:42, q:"How do I create a form or questionnaire?", a:"https://scribehow.com/page/Forms__Data_Collection__Mm0Gxjv6Rw6VskBZN-LNRw?referrer=documents", tags:"General,Admin"}
, {id:43, q:"How do I set up Stripe to accept credit card payments?", a:"https://scribehow.com/page/How_to_Setup_Stripe_for_Payments_in_LeagueLink__dMt1ieT9QOadcgjxsSpFgA", tags:"General,Admin"}
, {id:44, q:"What is Stripe?", a:"https://scribehow.com/page/Stripe_Requirements_for_LeagueLink__CQrAMbpWQpaYOaCWE7m7mA", tags:"General,Admin"}
, {id:45, q:"How do I mass assign a checklist? For example I want to assign Renewals to all active members.", a:"As of Feb 2026 there is no way to do this. However, a future upgrade is in the works.", tags:"Checklists,Admin"}
, {id:46, q:"Is it possible to use the Query Tool to look up form entries?", a:"Yes! At the very top right where it says your Chapter name, click it and change it to \"_National\".\nClick 'Administration', then 'Member Management', then 'Query Tool'.\nSearch for 'Form SQL Example'. Click edit to see the SQL query.\nNote: Don't forget to change the top-right option back to your own chapter!", tags:"Query,Admin"}
, {id:47, q:"Initial Import vs Supplemental Import: what's the difference?", a:"Initial Import is for importing records for accounts that do not exist in LeagueLink. Supplemental Import is for importing updates to existing records and requires different files depending on the fields you are updating because data is stored in different objects.", tags:"General,Admin"}
, {id:48, q:"I can't attend an event anymore. How do I cancel my registration?", a:"From the event page, click the button 'Cancel Registration' on the bottom of the page.", tags:"Calendar,Standard User"}
, {id:49, q:"How do I view all events?", a:"In the top nav click 'Calendar', then click the calendar you want (or click 'View All' to see all calendars)", tags:"Calendar,Standard User"}
, {id:50, q:"How do I see all the events I've registered for?", a:"On your homepage, the section labeled \"My Calendar\" lists all events that you've registered for.", tags:"Calendar,Standard User"}
, {id:51, q:"How do I add comments when registering for an event?", a:"On the event page just before the 'Register' button there is a comment box. When you register, these comments are saved along with your registration. If you don't see this, let an admin know and they can enable it. ", tags:"Calendar,Standard User"}
, {id:52, q:"How do I see a list of all members who have signed up for an event?", a:"Click 'Calendar', then click the calendar you want.\nClick the grey 'Manage' button at the top, then click 'List'.\nFind your event in the table. Under the column 'Attendees', click the icon that looks like 3 people.", tags:"Calendar,Admin"}
, {id:53, q:"For a calendar, how do I customize things like access, visible info, confirmation emails, reminder emails, default values, wait list, etc.?", a:"Click 'Calendar', then click the calendar you want.\nClick the grey 'Setup' button at the top.", tags:"Calendar,Admin"}
, {id:54, q:"What is Express Registration?", a:"When a user clicks on an event in the calendar, they will be registered for the event without even opening the event.", tags:"Calendar,Admin"}
, {id:55, q:"Why can't I add comments when I register for an event?", a:"Check your Calendar settings. Under \"Public/Guest Information\", either \"Allow Public Registration\" and \"Allow Guests?\" is set to Yes. Both options prevent registration comments.", tags:"Calendar,Admin"}
, {id:56, q:"How does someone get started becoming a new member?", a:"Send them this link:<a href='https://leaguelink.assistanceleague.org/?nd=user_volunteer_application&entry_point_type=global_entry_point&entry_point_id=3&unit_id=11&chapter_id=12 '>https://leaguelink.assistanceleague.org/?nd=user_volunteer_application&entry_point_type=global_entry_point&entry_point_id=3&unit_id=11&chapter_id=12 </a>", tags:"Membership,Admin"}
, {id:57, q:"In Calendar Setup, what does \"Advanced - Custom Detail Field\" do?", a:"This adds a custom value for each event in the calendar, for example if you wanted to add a Category to all events in a calendar. This field can only be set by an admin. The \"Type\" field determines who can see this field when viewing the event.", tags:"Calendar,Admin"}
, {id:58, q:"How do I collect responses/comments/notes from members when they register for an event, for example a pot luck?", a:"By default, a comment box is on the registration page. However, if you set a calendar's access to \"Allow Public Registration\" or \"Allow Guests\" then this comment box goes away. In this case, go to the calendar's setup and go to the section \"Advanced - General Settings\". Then set \"Select number of Custom Questions to include\" to 1 (or more). This custom question will be added to all events in a calendar.", tags:"Calendar,Admin"}
, {id:59, q:"I've set up Stripe by following the step-by-step guide and National has said it's ready. Why do I still not see anything different in my checklist?", a:"Go to your checklist step for \"Make a Dues Payment\".\nScroll down to the text box \"End User Link\" and paste this link: https://leaguelink.assistanceleague.org/?nd=vms_stripe_dues_landing", tags:"Dues,Checklist,Admin"}
, {id:60, q:"I just accepted a cash, check, or PayPal dues payment from a member. How do I process this?", a:"https://scribehow.com/viewer/Process_Dues_payments_with_Order_Management__6zddsl3PQgGyWjPzd4oEGQ", tags:"Dues,Admin"}
, {id:61, q:"How do I assign a checklist to a member?", a:"\"In the top nav click 'Administration' then 'Member Management'.\nClick 'Checklist Queue'.\nClick the '+' sign.\nUnder 'Checklist' select the Checklist you want to assign.\nUnder 'Account' search for the member name you want to assign the checklist to.", tags:"Checklists,Admin"}
, {id:62, q:"How do I mass assign a checklist (for example Renewals) to all active members?", a:"There is a special tool embedded in LeagueLink. In the top nav click 'Administration' then 'Member Management'.\nClick 'Query Tool' and search for the report called Checklist Assignment Tool - Renewal.\nSelect the members using the checkboxes next to their names.\nClick the icon at the top right that looks like a Bulleted List, then click 'Checklist Mass Assign'.\nUse the dropdown to select the appropriate checklist, then click Submit.\n", tags:"Checklists,Admin"}
, {id:63, q:"I've created a checklist where one of the steps is a form. When the user completes the form, how do I send the user back to the checklist?", a:"You can set the form's confirmation url as a checklist \"jump\" hyperlink. Go to your from and click the \"Set Up\" tab.\nScroll all the way down to the Form Confirmation section and in the \"Destination URL\" textbox enter the link http://leaguelink.assistanceleague.org/?nd=checklist_jump", tags:"Checklists,Forms,Admin"}
, {id:64, q:"How do the Access Group Conditions work? I want to include/exclude certain groups - are these conditions AND statements or OR statements?", a:"Both AND and OR. All the \"Include\" statements are collectively OR statements. All the \"Exclude\" statements are collectively OR statements. Together, the \"Include\" conditions and \"Exclude\" conditions are a single AND condition. Written out, it looks like this: ([Include] OR [Include] OR [Include]...) AND ([Exclude] OR [Exclude] OR [Exclude]...)", tags:"Groups,Admin"}
, {id:65, q:"I'm trying to pay for dues but I get the message \"You have already paid dues, check again when it is closer to your due date.\" Why?", a:"National has defined the membership renewal period as beginning April 1 (for membership starting on June 1). Therefore, LeagueLink uses this date to define who has paid/not paid. Please try again on or after April 1.", tags:"Membership,Standard User"}
, {id:66, q:"In the app, how do I use the Check-In feature to check-in members at an event using their Badge?", a:"Click the \"Check-In\" square.\nOn the top right, click the icon that looks like 3 people.\nSelect your event.\nClick \"Scan\". Then scan the member's Badge QR code.\nNote: You can modify how users check in to an event in the calendar's settings (not event settings). For example, whether to allow members to self check-in or not.", tags:"Calendar,Admin,App"}
, {id:67, q:"In the app, what does Badge do?", a:"Badge displays your unique member QR code. This can be used at events where the coordinator can check you in using your QR code.", tags:"Calendar,Standard User,App"}
, {id:68, q:"In checklists, what are some helpful \"End User Links\" for Admins that can be used to streamline checklists?", a:"https://scribehow.com/page/Commonly_Used_Hard_to_Find_LinksURLs__aez-yz6uQeq5Q18iIU7E6A?referrer=page&slug=/page/Member_and_Dues_Management__41AlR8ruRz64zD9x28H0Xg?referrer=documents", tags:"Checklists,Admin"}
, {id:69, q:"Help! When I click on an event, it automatically registers me for the event instead of simply opening it. How do I change this?", a:"Notify an admin. They will fix this setting.", tags:"Calendar,Standard User"}
, {id:70, q:"Help! I created a calendar and when I click on an event, it automatically registers me for the event instead of simply opening it. How do I change this?", a:"Click Administration > Member Management > Registration Tool Manager\nFind your calendar and click 'Setup'\nFind the dropdown labeled Express Registration and ensure it is set to 'Disabled'", tags:"Calendar,Admin"}

];

